//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект2
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Инвентарь> Инвентарь { get; set; }
        public virtual DbSet<Новый_инвентарь_со_склада> Новый_инвентарь_со_склада { get; set; }
        public virtual DbSet<Новый_материал_со_склада> Новый_материал_со_склада { get; set; }
        public virtual DbSet<Образование> Образование { get; set; }
        public virtual DbSet<Отдел> Отдел { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Событие> Событие { get; set; }
        public virtual DbSet<Учёт_инвентаря> Учёт_инвентаря { get; set; }
        public virtual DbSet<Учёт_материалов> Учёт_материалов { get; set; }
        public virtual DbSet<Фильтр> Фильтр { get; set; }
        public virtual DbSet<Материал> Материал { get; set; }
        public IEnumerable<object> Extradition { get; internal set; }
    }
}
