//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвентарь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Инвентарь()
        {
            this.Учёт_инвентаря = new HashSet<Учёт_инвентаря>();
        }
    
        public int Код_инвентаря { get; set; }
        public string Занятость { get; set; }
        public string Название { get; set; }
        public string Состояние { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт_инвентаря> Учёт_инвентаря { get; set; }
    }
}
