//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал()
        {
            this.Учёт_материалов = new HashSet<Учёт_материалов>();
        }
    
        public int Код_материала { get; set; }
        public string Название { get; set; }
        public string Состояние { get; set; }
        public string Количество { get; set; }
        public string фото { get; set; }
        public Nullable<int> Фильтр { get; set; }
        public bool Наличие { get; set; }

        public virtual Фильтр Фильтр1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт_материалов> Учёт_материалов { get; set; }
        public virtual ICollection<Фильтр> Фильтр2 { get; set; }

    }
}
