//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователь()
        {
            this.Учёт_инвентаря = new HashSet<Учёт_инвентаря>();
            this.Учёт_материалов = new HashSet<Учёт_материалов>();
        }
    
        public int Код_пользователя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public string Военный_билет { get; set; }
        public Nullable<int> Вид_образования { get; set; }
        public string Трудовая_книга { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public Nullable<int> Код_отдела { get; set; }
        public Nullable<int> Код_склада { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Фото { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Образование Образование { get; set; }
        public virtual Отдел Отдел { get; set; }
        public virtual Склад Склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт_инвентаря> Учёт_инвентаря { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт_материалов> Учёт_материалов { get; set; }
    }
}
