//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учёт_материалов
    {
        public System.DateTime Дата_и_время { get; set; }
        public int Код_материала { get; set; }
        public int Код_пользователя { get; set; }
        public int Вид_события { get; set; }
        public int Количество { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Событие Событие { get; set; }
        public virtual Материал Материал { get; set; }
    }
}
